enum EDITOR_ACTION{
}

enum ROOM_ACTION{
    SEND_MESSAGE='SEND_MESSAGE',
    CONNECT_TO_ROOM='CONNECT_TO_ROOM',
    USER_CONNECTED='USER_CONNECTED',
    CODE_CHANGED='CODE_CHANGED'
}
export {
    EDITOR_ACTION,
    ROOM_ACTION
}
