import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SynCode</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center w-screen h-screen bg-main-bg">
        <div className="h-[25rem] justify-between flex flex-col w-[20rem] border border-accent bg-accent2">
          <div className="">
            <p className="py-2 text-2xl text-center text-white">SynCode</p>
            <p className="px-4 pt-2 text-sm text-center text-white">Perfect tool for online coding with friends </p>
          </div>
          <div className="flex flex-col w-full mb-10 text-white gap-6">
            <Link className="py-1 text-center border border-transparent hover:border hover:border-t-accent hover:border-b-accent" href={"/register"}>Sign Up</Link>
            <Link className="py-1 text-center border border-transparent hover:border hover:border-t-accent hover:border-b-accent" href={"/login"}>Log In</Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
