import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {useRouter} from "next/router";
import {useForm} from 'react-hook-form'
import  {zodResolver} from '@hookform/resolvers/zod'
import React, {  useCallback, useState } from "react";
import { api } from "../utils/api";
import {ILogin,loginSchema} from "../schemas/auth";
const Home: NextPage = () => {
  // const [input, setInput] = useState({
  //   email: "",
  //   password: "",
  // });
    const router=useRouter()

    //
    const {mutateAsync} = api.user.loginUser.useMutation({
        onSuccess:(data)=>{
            console.log('SUCCESS',data);
        },
        onError:(data)=>{
            console.log('ERROR',data)
        }
        
    })
    const {register,handleSubmit} = useForm<ILogin>({
        resolver:zodResolver(loginSchema) 
    })
    const onSubmit=useCallback(async(data:ILogin)=>{
        try {
           await mutateAsync(data) 
        } catch (error) {
           console.log(error) 
        }
    },[])


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center min-h-screen bg-gray-300">
        <div className="flex flex-col w-1/3 bg-white border h-72 rounded-md border-gray-50">
          <p className="text-center text-black"> Colab Editor</p>
            <Link href="/login" 

              className="flex justify-center text-xs font-bold text-red-500"
                    >Login</Link>
        </div>
      </main>
    </>
  );
};

export default Home;
